# Generated by Django 5.1.7 on 2025-12-07 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('api_key', models.CharField(blank=True, max_length=100, unique=True)),
                ('accepts_natcash', models.BooleanField(default=False)),
                ('accepts_moncash', models.BooleanField(default=False)),
                ('natcash_name', models.CharField(blank=True, max_length=100, null=True)),
                ('natcash_number', models.CharField(blank=True, max_length=20, null=True)),
                ('moncash_name', models.CharField(blank=True, max_length=100, null=True)),
                ('moncash_number', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
